# Generated by Django 4.2.7 on 2023-11-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coresetting',
            old_name='time_execute',
            new_name='time_to_execute',
        ),
    ]
