# Generated by Django 4.2.7 on 2023-11-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_time_execute_coresetting_time_to_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresetting',
            name='facebook',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coresetting',
            name='instagram',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coresetting',
            name='twitter',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
