# Generated by Django 4.2.7 on 2023-11-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coresetting_facebook_coresetting_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coresetting',
            name='time_to_execute',
        ),
    ]
